### ISSUE TITLE
Change security code field background color

### ISSUE THREAD

**Issue by laurentpellegrino** [medicalid/issues#132]
> The app is well done. You can enter everything important and more. On my device I have the following problem: If you call the app, if a password is set, the code should be entered. However, the field for the code is not visible because it is dark. For the helper, a white field is better known. Can you change that?

**Comment by lpellegr** [comment]
Fixed by https://github.com/lpellegr/medicalid/commit/9850a71972418b7bf0cbcbcc12e4b0a20299f428.
