### ISSUE TITLE
App cannot be opened from lockscreen on Samsung S8+

### ISSUE THREAD

**Issue by laurentpellegrino** [medicalid/issues#141]
> I don't use any of the app widgets because the Samsung Galaxy S8 has an implemented setting that allows to start two apps directly from the lock screen. And because your floating widget starts without prompting to unlock, I think it should no problem to do the same with the app shortcuts in the lock screen settings. I use the finger print to unlock the phone.

**Comment by lpellegr** [comment]
Cannot reproduce for now. 

However, I have noticed the following error report:

> Exception java.lang.RuntimeException: Unable to create service app.medicalid.services.LockscreenManagerService: java.lang.RuntimeException: Unknown error
> arrow_drop_down
> Caused by java.lang.RuntimeException: Unknown error
> android.os.BinderProxy.transactNative (Binder.java)
> android.os.BinderProxy.transact (Binder.java:628)
> android.hardware.ICameraService$Stub$Proxy.addListener (ICameraService.java:368)
> android.hardware.camera2.CameraManager$CameraManagerGlobal.connectCameraServiceLocked (CameraManager.java:857)
> android.hardware.camera2.CameraManager$CameraManagerGlobal.registerAvailabilityCallback (CameraManager.java:1101)
> android.hardware.camera2.CameraManager.registerAvailabilityCallback (CameraManager.java:140)
> app.medicalid.services.LockscreenManagerService.onCreate ()
> android.app.ActivityThread.handleCreateService (ActivityThread.java:3532)
> android.app.ActivityThread.-wrap6 (ActivityThread.java)
> android.app.ActivityThread$H.handleMessage (ActivityThread.java:1743)
> android.os.Handler.dispatchMessage (Handler.java:102)
> android.os.Looper.loop (Looper.java:154)
> android.app.ActivityThread.main (ActivityThread.java:6724)
> java.lang.reflect.Method.invoke (Method.java)
> com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1520)
> com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1410)

**Comment by laurentpellegrino** [comment]
Not fixed

**Comment by laurentpellegrino** [comment]
The lock screen notification has been replaced by a floating icon that works smoothly on Android 22+.
