### ISSUE TITLE
Where do I add/link contacts to the MedicalID app?

### ISSUE THREAD

**Issue by hobiecats** [medicalid/issues#190]
Where do I add/link contacts to the MedicalID app?

It's not in any of the setting or the edit profile screen. Am I missing something??

I paid for this app so I really need to know how to add emergency contacts.

**Comment by laurentpellegrino** [comment]
@hobiecats Hello,

Thanks for your message.

Below is a link to a video that shows how to define ICE contacts:

https://www.youtube.com/watch?v=yz2F9qz7MLA

For managing alert contacts (i.e. contacts where the SMS alert is sent), open the app from the app launcher (not the launch screen), then tap on the 3 dots icons on the top right side, select _Settings_, _Alerts_, _SMS alert contacts_.

Please let me know if you need further assistance.

**Comment by hobiecats** [comment]
Thank you. That worked. 

I would just suggest that you make adding emergency contacts a bit more obvious, as someone like me just can't seem to figure it out on my own. I had no idea I had to watch the video for the instructions. But maybe that's just me. :-)

**Comment by laurentpellegrino** [comment]
@hobiecats You are welcome. Better onboarding and possibly dedicated fields for defining emergency contacts is something I plan to improve in the future but I cannot share any timeline.

Have a nice day.
