### ISSUE TITLE
Medical ID: ICE availability on Samsung Tab S2 with Android V7.0

### ISSUE THREAD

**Issue by nicolgrp** [medicalid/issues#202]
I have installed Medical ID; ICE on Samsung Galaxy S6 with Android 7.0 and decided to put it on my Samsung Tab S2 SM-T713since I travel with it as well.  However, when I search for the app on the Play Store with the Tab S2, it doesn't seem to be available.   

Is there a design restriction in the Medical ID: ICE app.  Or does some parameter need to be set on in Play Store  to make it available.  Perhaps it's just an oversight.

Very frustrating.  What are the options? If any.

**Comment by laurentpellegrino** [comment]
@nicolgrp Thanks for reaching out.

Can you see an install button if you open the next page from the device where you want the app?

https://play.google.com/store/apps/details?id=app.medicalid

**Comment by laurentpellegrino** [comment]
Old versions of the app are now available from Google Play for old devices that are no longer supported with the latest version.
