### ISSUE TITLE
Appstart with Systemstart

### ISSUE THREAD

**Issue by schissern** [medicalid/issues#36]
Is it possible to make the app start with the system?

**Comment by laurentpellegrino** [comment]
Do you mean having the Medical ID notification or the second lock screen layer that appears automatically when the device boot? If yes, this should already be the case. I just checked on Android version 6 and 7 using Medical ID in version 4.2.0. It is working as expected.

@schissern What is you device model and Android version?

**Comment by schissern** [comment]
Hmm, interesting. Now it's working, but beginning of the week it wasn't....

**Comment by laurentpellegrino** [comment]
Ok. Please let me know if the issue reappear.
