### ISSUE TITLE
Upgrade from free to paid version may break the app

### ISSUE THREAD

**Issue by laurentpellegrino** [medicalid/issues#37]
A user has reported a failure during the upgrade process from the free to paid version. It seems that a single profile was present in the free version when the paid one was installed. Once the upgrade was completed, the user noticed there was 21 profiles in listed on the paid version. 

I have also received some crash reports that let suppose some values were corrupted in the database. 

Should try to reproduce and fix as soon as possible.

Device from user is HTC One M9 (htc_himauhl). Android version 6.0.0.

**Comment by lpellegr** [comment]
Cannot reproduce.
