### ISSUE TITLE
Backup feature? Local/Dropbox/Google Drive

### ISSUE THREAD

**Issue by Wixxi** [medicalid/issues#65]
Hey  I helped you translate your Medical ID app to dutch.
One major feature I'm missing is backup to dropbox/google drive or just local.
Just switched phones and had to retyp everything.
And an export to just text isn't that usefull.

You think you can add this in an update soon?

Greetz,
Jens

**Comment by laurentpellegrino** [comment]
Yes, will definitively be added.

Duplicate of https://github.com/medicalid/issues/issues/53.
